src/main/java/com/homeadvisor/kafdrop/model/ConsumerTopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

public class ConsumerTopicVO
{
   private final String topic;
   private final Map<Integer, ConsumerPartitionVO> offsets = new TreeMap<>();

   public ConsumerTopicVO(String topic)
   {
      this.topic = topic;
   }

   public String getTopic()
   {
      return topic;
   }

   public void addOffset(ConsumerPartitionVO offset)
   {
      offsets.put(offset.getPartitionId(), offset);
   }

   public long getLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::sum);
   }

   public long getMaxLag()
   {
      return offsets.values().stream()
         .map(ConsumerPartitionVO::getLag)
         .filter(lag -> lag >= 0)
         .reduce(0L, Long::max);
   }

   public Collection<ConsumerPartitionVO> getPartitions()
   {
      return offsets.values();
   }

   public double getCoveragePercent()
   {
      return ((double)getAssignedPartitionCount()) / offsets.size();
   }

   public int getAssignedPartitionCount()
   {
      return (int) offsets.values().stream()
         .filter(p -> p.getOwner() != null)
         .count();
   }

   public int getOwnerCount()
   {
      return (int)offsets.values().stream()
         .map(ConsumerPartitionVO::getOwner)
         .filter(Objects::nonNull)
         .distinct()
         .count();
   }
}

src/main/java/com/homeadvisor/kafdrop/model/ConsumerVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import org.apache.commons.lang.Validate;

import java.util.*;
import java.util.stream.Collectors;

public class ConsumerVO implements Comparable<ConsumerVO>
{
   private String groupId;
   private Map<String, ConsumerTopicVO> topics = new TreeMap<>();
   private List<ConsumerRegistrationVO> activeInstances = new ArrayList<>();

   public ConsumerVO(String groupId)
   {
      Validate.notEmpty("groupId is required");
      this.groupId = groupId;
   }

   public String getGroupId()
   {
      return groupId;
   }

   public void setGroupId(String groupId)
   {
      this.groupId = groupId;
   }

   public void addActiveInstance(ConsumerRegistrationVO id)
   {
      activeInstances.add(id);
   }

   public List<ConsumerRegistrationVO> getActiveInstances()
   {
      return activeInstances;
   }

   public List<ConsumerRegistrationVO> getActiveInstancesForTopic(String topic)
   {
      return activeInstances.stream()
         .filter(reg -> reg.getSubscriptions().containsKey(topic))
         .collect(Collectors.toList());
   }

   public void addTopic(ConsumerTopicVO topic)
   {
      topics.put(topic.getTopic(), topic);
   }

   public ConsumerTopicVO getTopic(String topic)
   {
      return topics.get(topic);
   }

   public Collection<ConsumerTopicVO> getTopics()
   {
      return topics.values();
   }

   public int getActiveTopicCount()
   {
      return topics.values().stream()
         .map(t -> t.getAssignedPartitionCount() > 0 ? 1 : 0)
         .reduce(0, Integer::sum);
   }

   @Override
   public int compareTo(ConsumerVO that)
   {
      return this.groupId.compareTo(that.groupId);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      ConsumerVO vo = (ConsumerVO) o;

      if (!groupId.equals(vo.groupId)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return groupId.hashCode();
   }

}

src/main/java/com/homeadvisor/kafdrop/model/TopicVO.java
/*
 * Copyright 2017 HomeAdvisor, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.homeadvisor.kafdrop.model;

import java.util.*;
import java.util.stream.Collectors;

public class TopicVO implements Comparable<TopicVO>
{
   private String name;
   private Map<Integer, TopicPartitionVO> partitions = new TreeMap<>();
   private Map<String, Object> config = new TreeMap<>();
   // description?
   // partition state
   // delete supported?


   public TopicVO(String name)
   {
      this.name = name;
   }

   public String getName()
   {
      return name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public Map<String, Object> getConfig()
   {
      return config;
   }

   public void setConfig(Map<String, Object> config)
   {
      this.config = config;
   }

   public Collection<TopicPartitionVO> getPartitions()
   {
      return partitions.values();
   }

   public Optional<TopicPartitionVO> getPartition(int partitionId)
   {
      return Optional.ofNullable(partitions.get(partitionId));
   }

   public Collection<TopicPartitionVO> getLeaderPartitions(int brokerId)
   {
      return partitions.values().stream()
         .filter(tp -> tp.getLeader() != null && tp.getLeader().getId() == brokerId)
         .collect(Collectors.toList());
   }

   public Collection<TopicPartitionVO> getUnderReplicatedPartitions()
   {
      return partitions.values().stream()
         .filter(TopicPartitionVO::isUnderReplicated)
         .collect(Collectors.toList());
   }

   public void setPartitions(Map<Integer, TopicPartitionVO> partitions)
   {
      this.partitions = partitions;
   }

   /**
    * Returns the total number of messages published to the topic, ever
    * @return
    */
   public long getTotalSize()
   {
      return partitions.values().stream()
         .map(TopicPartitionVO::getSize)
         .reduce(0L, Long::sum);
   }

   /**
    * Returns the total number of messages available to consume from the topic.
    * @return
    */
   public long getAvailableSize()
   {
      return partitions.values().stream()
         .map(p -> p.getSize() - p.getFirstOffset())
         .reduce(0L, Long::sum);
   }

   public double getPreferredReplicaPercent()
   {
      long preferredLeaderCount = partitions.values().stream()
         .filter(TopicPartitionVO::isLeaderPreferred)
         .count();
      return ((double) preferredLeaderCount) / ((double)partitions.size());
   }

   public void addPartition(TopicPartitionVO partition)
   {
      partitions.put(partition.getId(), partition);
   }

   @Override
   public int compareTo(TopicVO that)
   {
      return this.name.compareTo(that.name);
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      TopicVO that = (TopicVO) o;

      if (!name.equals(that.name)) return false;

      return true;
   }

   @Override
   public int hashCode()
   {
      return name.hashCode();
   }

}

src/main/resources/templates/broker-detail.ftl
<#import "lib/template.ftl" as template>
<@template.header "Broker: ${broker.id?string}">
<style type="text/css">
    .bs-table.overview td { white-space: nowrap; }

    td.leader-partitions { word-break: break-all; }

</style>
</@template.header>

<#setting number_format="0">

<h1>Broker Id: ${broker.id}</h1>

<div id="topic-overview">
    <h2>Broker Overview</h2>

    <table class="bs-table default overview">
        <tbody>
        <tr>
            <td><i class="fa fa-laptop"></i> Host</td>
            <td>${broker.host}:${broker.port}</td>
        </tr>
        <tr>
            <td><i class="fa fa-clock-o"></i> Start Time</td>
            <td>${broker.timestamp?string["yyyy-MM-dd HH:mm:ss.SSSZ"]}</td>
        </tr>
        <tr>
            <td>Controller</td>
            <td><@template.yn broker.controller/></td>
        </tr>
        <tr>
            <td># of Topics</td>
            <td>${topics?size}</td>
        </tr>

        <#assign partitionCount=0>
        <#list topics as t>
            <#assign partitionCount=partitionCount+(t.getLeaderPartitions(broker.id)?size)>
        </#list>
        <tr>
            <td># of Partitions</td>
            <td>${partitionCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div>
    <h2>Topic Detail</h2>

    <table class="bs-table default">
        <thead>
        <tr>
            <th>Topic</th>
            <th>Total Partitions</th>
            <th>Broker Partitions</th>
            <th>Partition Ids</th>
        </tr>
        </thead>
        <tbody>
        <#list topics as t>
              <tr>
                  <td><a href="/topic/${t.name}">${t.name}</a></td>
                  <td>${t.partitions?size}</td>
                  <td>${t.getLeaderPartitions(broker.id)?size}</td>
                  <td class="leader-partitions"><#list t.getLeaderPartitions(broker.id) as p>${p.id}<#sep>,</#list></td>
              </tr>
        </#list>
        </tbody>
    </table>
</div>

<br>
</div>
</body>
</html>

src/main/resources/templates/cluster-overview.ftl
<#import "lib/template.ftl" as template>
<@template.header "Broker List"/>

<#setting number_format="0">
    <div>
        <h2>Kafka Cluster Overview</h2>

        <div id="zookeeper">
            <b>Zookeeper Hosts:</b> <#list zookeeper.connectList as z>${z}<#if z_has_next>, </#if></#list>
        </div>

        <div id="brokers">
            <h3>Brokers</h3>
            <table class="bs-table default">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Host</th>
                    <th>Port</th>
                    <th>JMX Port</th>
                    <th>Version</th>
                    <th>Start Time</th>
                    <th>Controller?</th>
                    <th>Health Status</th>
                </tr>
                </thead>
                <tbody>
                <#if brokers?size == 0>
                    <tr>
                        <td class="error" colspan="7">No brokers available!</td>
                    </tr>
                </#if>
                <#list brokers as b>
                <tr>
                    <td><a href="/broker/${b.id}"><i class="fa fa-info-circle fa-lg"></i> ${b.id}</a></td>
                    <td>${b.host}</td>
                    <td>${b.port?string}</td>
                    <td>${b.jmxPort?string}</td>
                    <td>${b.version}</td>
                    <td>${b.timestamp?string["yyyy-MM-dd HH:mm:ss.SSSZ"]}</td>
                    <td><@template.yn b.controller/></td>
                    <td>${b.healthStatus}</td>
                </tr>
                </#list>
                </tbody>
            </table>
        </div>

        <div id="topics">
            <h3>Topics</h3>
            <table class="bs-table default">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Partitions</th>
                    <th>% Preferred</th>
                    <th># Under Replicated</th>
                    <th>Custom Config?</th>
                    <#--<th>Consumers</th>-->
                </tr>
                </thead>
                <tbody>
                <#if topics?size == 0>
                <tr>
                    <td colspan="5">No topics available</td>
                </tr>
                </#if>
                <#list topics as t>
                <tr>
                    <td><a href="/topic/${t.name}">${t.name}</a></td>
                    <td>${t.partitions?size}</td>
                    <td <#if t.preferredReplicaPercent lt 1.0>class="warn"</#if>>${t.preferredReplicaPercent?string.percent}</td>
                    <td <#if t.underReplicatedPartitions?size gt 0>class="warn"</#if>>${t.underReplicatedPartitions?size}</td>
                    <td><@template.yn t.config?size gt 0/></td>
                    <#--<td>${t.consumers![]?size}</td>-->
                </tr>
                </#list>
                </tbody>
            </table>
            <br>
        </div>
    </div>
<br>
</div>
</body>
</html>

src/main/resources/templates/consumer-detail.ftl
<#import "lib/template.ftl" as template>
<@template.header "Consumer: ${consumer.groupId}"/>

<#setting number_format="0">

<h1>Kafka Consumer: ${consumer.groupId}</h1>

<div id="overview">
    <h2>Overview</h2>
    <table class="bs-table default overview">
        <tbody>
        <tr>
            <td>Active Instances</td>
            <td>${consumer.activeInstances?size}</td>
        </tr>
        <tr>
            <td>Topics</td>
            <td>${consumer.topics?size}</td>
        </tr>
        <tr>
            <td>Active Topics</td>
            <td>${consumer.activeTopicCount}</td>
        </tr>
        </tbody>
    </table>
</div>

<div id="topics">
<#list consumer.topics as consumerTopic>
    <#assign tableId='topic-${consumerTopic_index}-table'>
    <h2><@template.toggleLink target="#${tableId}" anchor='${tableId}' /> Topic: <a href="/topic/${consumerTopic.topic}">${consumerTopic.topic}</a></h2>
    <div id="${tableId}">
        <p>
            <table class="bs-table default overview">
                <tbody>
                    <tr>
                        <td>Total Threads</td>
                        <td>${consumerTopic.ownerCount}</td>
                    </tr>
                    <tr>
                        <td>Partition Coverage</td>
                        <td>${consumerTopic.coveragePercent * 100.0}%
                            (${consumerTopic.assignedPartitionCount} of ${consumerTopic.partitions?size})</td>
                    </tr>
                    <tr>
                        <td>Total Lag</td>
                        <td>${consumerTopic.lag}</td>
                    </tr>
                    <tr>
                        <td>Max Lag</td>
                        <td>${consumerTopic.maxLag}</td>
                    </tr>
                </tbody>
            </table>
        </p>
        <p>
            <table class="bs-table small">
                <thead>
                <tr>
                    <th>Partition</th>
                    <th>First Offset</th>
                    <th>Last Offset</th>
                    <th>Offset</th>
                    <th>Lag</th>
                    <th>Owner</th>
                </tr>
                </thead>
                <tbody>
                <#list consumerTopic.partitions as p>
                   <tr>
                       <td>${p.partitionId}</td>
                       <td>${p.firstOffset}</td>
                       <td>${p.size}</td>
                       <td>${p.offset}</td>
                       <td>${p.lag}</td>
                       <td>${p.owner!''}</td>
                   </tr>
                </#list>
                </tbody>
            </table>
        </p>
    </div>
</#list>

</div>

<br>
</div>
</body>
</html>

src/main/resources/templates/message-inspector.ftl
<#import "lib/template.ftl" as template>
<#import "/spring.ftl" as spring />
<@template.header "Topic: ${topic.name}: Messages">
   <style type="text/css">
       h1 { margin-bottom: 16px; }
       #messageFormPanel { margin-top: 16px; }
       #partitionSizes { margin-left: 16px; }
       .toggle-msg { float: left;}
   </style>

  <script src="/js/message-inspector.js"></script>
</@template.header>
<#setting number_format="0">


<h1 class="col threecol">Topic Messages: <a href="/topic/${topic.name}">${topic.name}</a></h1>

<#assign selectedPartition=messageForm.partition!0?number>

<div id="partitionSizes">
    <#assign curPartition=topic.getPartition(selectedPartition).get()>
    <span class="bs-label">First Offset:</span> <span id="firstOffset">${curPartition.firstOffset}</span>
    <span class="bs-label">Last Offset:</span> <span id="lastOffset">${curPartition.size}</span>
    <span class="bs-label">Size:</span> <span id="partitionSize">${curPartition.size - curPartition.firstOffset}</span>
</div>

<div id="messageFormPanel" class="bs-panel">
<form method="GET" action="/topic/${topic.name}/messages" id="messageForm" class="bs-form panel-body">

    <div class="bs-form-group inline">
        <label for="partition">Partition</label>
        <select id="partition" name="partition">
        <#list topic.partitions as p>
            <option value="${p.id}" data-first-offset="${p.firstOffset}" data-last-offset="${p.size}" <#if p.id == selectedPartition>selected="selected"</#if>>${p.id}</option>
        </#list>
        </select>

        <label for="offset">Offset</label>
        <@spring.bind path="messageForm.offset"/>
        <@spring.formInput path="messageForm.offset" attributes='class="bs-form-elem ${spring.status.error?string("error", "")}"'/>
        <@spring.showErrors separator="\n" classOrStyle="error"/>

        <label for="count">Num Messages</label>
        <@spring.bind path="messageForm.count"/>
        <@spring.formInput path="messageForm.count" attributes='class="bs-form-elem ${spring.status.error?string("error", "")}"'/>
        <span class="error"><@spring.showErrors "<br/>"/></span>

        <button class="bs-btn primary" type="submit"><i class="fa fa-search"></i> View Messages</button>

    </div>

</form>
</div>

<@spring.bind path="messageForm.*"/>
<div id="message-display">
    <#if messages?? && messages?size gt 0>
    <#list messages as msg>
        <#assign offset=messageForm.offset + msg_index>
        <div data-offset="${offset}" class="message-detail">
            <span class="bs-label">Offset:</span> ${offset}
            <span class="bs-label">Key:</span> ${(msg.key)!''}
            <span class="bs-label">Checksum/Computed:</span> <span <#if !msg.valid>class="error"</#if>>${msg.checksum}/${msg.computedChecksum}</span>
            <span class="bs-label">Compression:</span> ${msg.compressionCodec}
            <div>
            <a href="#" class="toggle-msg"><i class="fa fa-chevron-circle-right">&nbsp;</i></a>
            <pre class="message-body">${msg.message!''}</pre>
            </div>
        </div>
    </#list>
    <#elseif !(spring.status.error) && !(messageForm.empty)>
        No messages found in partition ${messageForm.partition} at offset ${messageForm.offset}
    </#if>
</div>

<br>
</div>
</body>
</html>

src/main/resources/templates/not-initialized.ftl
<#import "lib/template.ftl" as template>
<@template.header "Initializing...">
   <meta http-equiv="refresh" content="5" >
</@template.header>

<div>
    <p>Internal caches are still initializing. Please wait...</p>
</div>

<br>
</div>
</body>
</html>

src/main/resources/templates/topic-detail.ftl
<#import "lib/template.ftl" as template>
<@template.header "Topic: ${topic.name}">
  <style type="text/css">
      #action-bar { margin-top: 17px; }
      th { word-break: break-all; }
  </style>
</@template.header>

<#setting number_format="0">

<h1 class="col threecol">Topic: ${topic.name}</h1>

<div id="action-bar">
    <a class="bs-btn info" href="/topic/${topic.name}/messages"><i class="fa fa-eye"></i> View Messages</a>
</div>

<div class="row">

<div id="topic-overview" class="col fivecol">
    <h2>Overview</h2>

    <table class="bs-table default">
        <tbody>
        <tr>
            <td># of Partitions</td>
            <td>${topic.partitions?size}</td>
        </tr>
        <tr>
            <td>Preferred Replicas</td>
            <td <#if topic.preferredReplicaPercent lt 1.0>class="error"</#if>>${topic.preferredReplicaPercent?string.percent}</td>
        </tr>
        <tr>
            <td>Under Replicated Partitions</td>
            <td <#if topic.underReplicatedPartitions?size gt 0>class="error"</#if>>${topic.underReplicatedPartitions?size}</td>
        </tr>
        <tr>
            <td>Total Size</td>
            <td>${topic.totalSize}</td>
        </tr>
        <tr>
            <td>Total Available Messages</td>
            <td>${topic.availableSize}</td>
        </tr>
        </tbody>
    </table>
</div>


<div id="topic-config" class="col sevencol">
    <h2>Configuration</h2>

    <#if topic.config?size == 0>
    <div>No topic specific configuration</div>
    <#else>
    <table class="bs-table default">
        <tbody>
        <#list topic.config?keys as c>
              <tr>
                  <td>${c}</td>
                  <td>${topic.config[c]}</td>
              </tr>
        </#list>
        </tbody>
    </table>
    </#if>
</div>

</div>

<div class="row">
<div id="partition-detail" class="col fivecol">
    <h2>Partition Detail</h2>
    <table id="partition-detail-table" class="bs-table small">
        <thead>
        <tr>
            <th>Partition</th>
            <th>First Offset</th>
            <th>Last Offset</th>
            <th>Size</th>
            <th>Leader</th>
            <th>Replicas</th>
            <th>In Sync Replicas</th>
            <th>Preferred Leader?</th>
            <th>Under Replicated?</th>
        </tr>
        </thead>
        <tbody>
        <#list topic.partitions as p>
        <tr>
            <td>${p.id}</td>
            <td>${p.firstOffset}</td>
            <td>${p.size}</td>
            <td>${p.size - p.firstOffset}</td>
            <td <#if !(p.leader)??>class="error"</#if>>${(p.leader.id)!"none"}</td>
            <td><#list p.replicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td><#list p.inSyncReplicas as r>${r.id}<#if r_has_next>,</#if></#list></td>
            <td <#if !p.leaderPreferred>class="error"</#if>><@template.yn p.leaderPreferred/></td>
            <td <#if p.underReplicated>class="error"</#if>><@template.yn p.underReplicated/></td>
        </tr>
        </#list>
        </tbody>
    </table>
</div>

<div id="consumers" class="col sevencol">
    <h2>Consumers</h2>
    <table id="consumers-table" class="bs-table small">
        <thead>
        <tr>
            <th>Group Id</th>
            <th>Lag</th>
            <th>Active Instances</th>
        </tr>
        </thead>
        <tbody>
        <#list consumers![] as c>
            <tr>
                <td><a href="/consumer/${c.groupId}">${c.groupId}</a></td>
                <td>${c.getTopic(topic.name).lag}</td>
                <td>
                    <ul class="bs-list flat">
                       <#list c.getActiveInstancesForTopic(topic.name) as i>
                           <li>${i.id}</li>
                       </#list>
                    </ul>
                </td>
            </tr>
        </#list>
        </tbody>
    </table>
</div>
</div>
<br>
</div>
</body>
</html>